console.log("Самооценка моей работы: общая 150 балов, ниже расписано по пунктам:");
console.log("1. валидная +10");
console.log("2. семантическая(h1,h2,h3,h4,h5,h6,main,header,naw,footer,section) +20");
console.log("3. css-стили +10");
console.log("4. горизонтальный блок +10");
console.log("5. верстка адаптивная +10");
console.log("6. есть адаптивное меню +10");
console.log("7. есть фото с атрибутом alt +10");
console.log("8. котакты в виде списка +10");
console.log("9. СV по схеме +10");
console.log("10. есть пример кода js +10");
console.log("11. на проекты ссылок нет т.к. нет проектов, если бы были, то сделал бы +10");
console.log("12. CV in English js +10");
console.log("13. требования к Pull Request +10");
console.log("14. видеорезюме нет:(  +0");
console.log("15. дизайн, оформление, качество выполнения CV отличное:)  +10");